# -*- coding: utf-8 -*-
"""Código Python para Sorteio Aleatório Simples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bg7OB75zddCvFOLZx7xbY0Wq5eZFFQx9
"""

import random

total_populacao = 715

tamanho_amostra = 32

populacao = list(range(1, total_populacao + 1))

if tamanho_amostra > total_populacao:
    print("Erro: O tamanho da amostra não pode ser maior que a população total.")
else:

    amostra_sorteada = random.sample(populacao, tamanho_amostra)

    print("--- RESULTADO DO SORTEIO ALEATÓRIO SIMPLES ---")
    print(f"População Total: {total_populacao} participantes.")
    print(f"Tamanho da Amostra Sorteada: {tamanho_amostra} participantes.\n")
    print("Os identificadores dos participantes selecionados para a amostra são:")

    print(sorted(amostra_sorteada))